services:
  postgres-test:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_DB: pokedex_test
      POSTGRES_USER: pokedex_user
      POSTGRES_PASSWORD: pokedex_password
    ports:
      - '5434:5432' # Different port to avoid conflicts
    command: postgres -c max_connections=100 -c shared_buffers=128MB
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pokedex_user -d pokedex_test']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./init-test.sql:/docker-entrypoint-initdb.d/init-test.sql
