name: E2E Tests

on:
  workflow_call:
    inputs:
      cached-build-id:
        description: "ID for cached build"
        required: true
        type: string

jobs:
  e2e-checks:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Restore Build
        uses: actions/cache/restore@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ inputs.cached-build-id }}

      - name: Install Playwright
        run: npm run test:e2e:install

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
