name: E2E Tests

on:
  workflow_call:
    inputs:
      cached-build-id:
        description: "ID for cached build"
        required: true
        type: string

jobs:
  e2e-checks:
    name: E2E Tests
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: pokedex_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Restore Build
        uses: actions/cache/restore@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ inputs.cached-build-id }}

      - name: Install Playwright
        run: npm run test:e2e:install

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: test-results/
          retention-days: 30
